### ISSUE TITLE
Syntax errors in dynamic pages

### ISSUE THREAD

**Issue by bnmnetp** [barbarer/ThinkCPP#13]
```
Traceback (most recent call last):
  File "/home/bmiller/Runestone/web2py/gluon/main.py", line 444, in wsgibase
    serve_controller(request, response, session)
  File "/home/bmiller/Runestone/web2py/gluon/main.py", line 183, in serve_controller
    page = run_view_in(response._view_environment)
  File "/home/bmiller/Runestone/web2py/gluon/compileapp.py", line 733, in run_view_in
    ccode = compile2(scode, filename)
  File "/home/bmiller/Runestone/web2py/gluon/restricted.py", line 205, in compile2
    return compile(code, layer, 'exec')
  File "/home/bmiller/Runestone/web2py/applications/runestone/books/thinkcpp/published/thinkcpp/Chapter8/structures_as_returns_types.html", line 62
    </span><span class="n">x</span><span class="p">,</span> <span class="n">y</span><span class="p">},</span> <span class="n">x</span><span class="p">,</span> <span class="n">y</span><span class="p">};</span>
    ^
SyntaxError: invalid syntax
```

This comes from code that has `{{` They need to be separated by a space or an invisible space or else the page will not render.

**Comment by barbarer** [comment]
We fixed this.  Thanks for finding it.
